from ubuntu:14.04

maintainer Nate Jones <nate@endot.org>

run apt-get update
run DEBIAN_FRONTEND=noninteractive apt-get install libevent-dev ncurses-dev build-essential wget -y
run mkdir /tmux

add build.sh /tmux/build.sh
